# Generated by Django 4.1.13 on 2024-05-11 10:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import books.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'объект "Автор"',
                'verbose_name_plural': 'Автора',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Идентификатор')),
                ('description', models.TextField(blank=True, help_text='Поле может быть пустым', null=True, verbose_name='Описание')),
                ('year_of_publication', models.PositiveSmallIntegerField(validators=[books.validators.validate_year_of_publication], verbose_name='Год издания')),
                ('page_count', models.PositiveSmallIntegerField(help_text='Укажите количество страниц от 1 до 5000', validators=[django.core.validators.MinValueValidator(1, 'Ошибка! Минимальное значение = 1'), django.core.validators.MaxValueValidator(5000, 'Ошибка! Максимальное значение = 5000')], verbose_name='Количество страниц')),
                ('isbn', models.CharField(help_text='Введите ISBN в формате: 978-5-93673-265-2', max_length=17, validators=[django.core.validators.RegexValidator(message='Ошибка! Проверьте вводимый формат', regex='^\\d{3}-\\d{1}-\\d{5}-\\d{3}-\\d{1}$')], verbose_name='ISBN')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'объект "Книга"',
                'verbose_name_plural': 'Книги',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'объект "Жанр"',
                'verbose_name_plural': 'Жанры',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'объект "Издательство"',
                'verbose_name_plural': 'Издательства',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'объект "Серия"',
                'verbose_name_plural': 'Серии',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('rating', models.PositiveSmallIntegerField(help_text='Укажите рейтинг книги от 1 до 10', validators=[django.core.validators.MinValueValidator(1, 'Ошибка! Минимальное значение = 1'), django.core.validators.MaxValueValidator(10, 'Ошибка! Максимальное значение = 10')], verbose_name='Рейтинг')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'объект "Отзыв"',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'объект "Избранное"',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.publisher', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.series', verbose_name='Серия'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'book'), name='unique_author_book'),
        ),
        migrations.AddConstraint(
            model_name='favourites',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book'),
        ),
    ]
