MAX_LENGTH_FIELDS_OF_NAME_AND_SLUG = 255

MIN_VALIDATION_VALUE_OF_PAGE_COUNT = 1

MAX_VALIDATION_VALUE_OF_PAGE_COUNT = 5000

MAX_LENGTH_FIELDS_OF_ISBN = 17

MAX_LENGTH_FIELDS_OF_EMAIL = 254

MAX_LENGTH_FIELDS_OF_NAME = 100

MAX_LENGTH_FIELDS_OF_USERNAME = 20

MAX_LENGTH_FIELDS_OF_GENDER = 7
